### ISSUE TITLE
Even distribution over time

### ISSUE THREAD

**Issue by objectiveSee** [jhurliman/node-rate-limiter#11]
If I specify 20 / minute, and I have thousands of requests per second (for example).  Right now I see 20 events happen right away, then nothing for 1 minute, then another burst of 20 events.  It would be nice to specify an option for an even distribution so that one event would fire every 3 seconds rather than bursting every minute.

Thanks!

**Comment by MariusRumpf** [comment]
This works with 20 requests per minute, but if you have a limit of 500 per day this is not a solution. This would mean I have a setting of 0.005787 per second. :+1: for an even distribution setting.

**Comment by Belenus** [comment]
@MariusRumpf This can be achieved, again, with a little more work on your side.  500 requests per day is equivalent to 1 request every 172.8 seconds(172800 in milliseconds).

This will instantiate a limiter at an evenly distributed rate of 500requests/24hours:
```javascript
var limiter = new RateLimiter(1, 172800);
```

**Comment by jhurliman** [comment]
Since I believe @Belenus's answer addresses this question I'm closing the ticket. Feel free to reopen if I overlooked something.
