### ISSUE TITLE
Add non-leaky bucket implementation

### ISSUE THREAD

**Issue by mattrick16** [jhurliman/node-rate-limiter#14]
Hello, I think it may be a good idea to include a non-leaky bucket implementation. Instead of it eventually doing the intended action, just block the action altogether.

**Comment by jhurliman** [comment]
@mattrick16 that sounds like a great idea. I won't have time to do the implementation by myself in the near future, but if anyone does start working on it please let me know in this ticket.

**Comment by jhurliman** [comment]
Actually, this should already be possible with `tryRemoveTokens`. It's a synchronous method that will return false if the requested number of tokens could not be removed.
