### ISSUE TITLE
Support for out of process cache (e.g. redis)

### ISSUE THREAD

**Issue by i0natan** [jhurliman/node-rate-limiter#54]
To prevent brute-force in a multi-server scenario the cache/tokens should be store in some external storage, do you support this?

**Comment by goldiloxio** [comment]
@i0natan I was researching the same thing and just found this [plugin](https://github.com/mujichOk/node-rate-limiter-redis) - haven't tried it yet.

**Comment by jhurliman** [comment]
No, this project is intended to be a pure JS implementation with no dependencies or (built-in) interfaces to backing data stores. If you are looking for an all-in-one solution that coordinates across distributed systems, take a look at https://github.com/Tabcorp/redis-rate-limiter
