### ISSUE TITLE
Rate limit by Parameter

### ISSUE THREAD

**Issue by bgold0** [jhurliman/node-rate-limiter#60]
I'm assuming this is by IP? Is there anyway I can insert via the options like a parameter to use instead?

For example right now it is set up to not allow more then 5 requests per IP address per minute. But right now I'm hoping to make it by email.

**Comment by jhurliman** [comment]
All of that is part of your application design, and is out of scope for this library which only handles the actual tracking of rate limiters and does not know about IP addresses or emails.
