### ISSUE TITLE
Would this project be open to a PR adding asyncRemoveTokens?

### ISSUE THREAD

**Issue by sunknudsen** [jhurliman/node-rate-limiter#63]
I have been wrapping `removeTokens` in a promise (as suggested in https://github.com/jhurliman/node-rate-limiter/issues/52) for a while.

Feels like it would be clean and useful if we implemented an `asyncRemoveTokens` method.

```typescript
function asyncRemoveTokens(count: number, rateLimiter: RateLimiter) {
  return new Promise((resolve, reject) => {
    rateLimiter.removeTokens(count, (error, remainingRequests) => {
      if (error) return reject(error)
      resolve(remainingRequests)
    })
  })
}
```

**Comment by jhurliman** [comment]
Sure! I think this could be a member of `RateLimiter`

**Comment by jhurliman** [comment]
Done in 2.0.0
